# Fetch and use the latest Fastfile from the fastlane main repository
import("../../fastlane/Fastfile")

desc("builds for screengrab")
  lane :build_for_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
end

lane(:deploy_aar) do
  ensure_git_branch
  ensure_git_status_clean

  gradle(task: [
    'screengrab-lib:clean',
    'screengrab-lib:assembleRelease',
    'screengrab-lib:bintrayUpload',
    '-PdryRun=false'
  ].join(' '))
end
